title:              The dataslice demo
email:              shackcentral2@gmail.com
description:        A Blog Theme by Start Bootstrap
author:             iamshacky
baseurl:            ""
url:                ""

# Social Profiles
twitter_username:   
github_username:    iamshacky
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# themes
theme: jekyll-theme-clean-blog

# incremental
incremental: true
